import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { SearchInput } from "../components";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	const [search, setSearch] = useState("");
	const router = useRouter();

	const searchInputOnChange = (value: string) => {
		setSearch(value);
	};

	const searchInputOnKeyDown = () => {
		router.push(`/search/${search}`);
	};

	return (
		<>
			<Head>
				<title>Spotify Explorer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
					rel="stylesheet"
				/>
			</Head>

			<div className={styles.container}>
				<div className="relative top-1/4">
					<span className="text-7xl text-center text-green-spotify">Spotify</span>
					<br />
					<h1 className="text-7xl text-center text-white mb-10">Explorer</h1>
					<SearchInput onChange={searchInputOnChange} onKeyDown={searchInputOnKeyDown} />
				</div>
			</div>
		</>
	);
};

export default Home;
